packages:
  - packages/*
  - playground/*
  - docs

catalog:
  '@vueuse/core': ^11.0.3
  '@arco-design/web-vue': ^2.56.1
  '@vrx-arco/color-picker': ~0.0.1-beta.12
  '@vrx-arco/color-picker-import-resolver': ~0.0.1-beta.12
  unplugin-vue-components: ^0.27.4
