packages:
  - packages/*
  - playground/*
  - docs
catalog:
  '@arco-design/web-vue': ^2.56.3
  '@vrx-arco/color-picker': ~0.0.1
  '@vrx-arco/color-picker-import-resolver': ~0.0.1
  '@vrx-arco/icons-vue': ^0.3.1
  '@vueuse/core': ^12.2.0
  unplugin-vue-components: ^0.28.0
