packages:
  - packages/*
  - playground/*
  - docs
catalog:
  '@arco-design/web-vue': ^2.57.0
  '@vrx-arco/color-picker': ~0.0.1
  '@vrx-arco/color-picker-import-resolver': ~0.0.1
  '@vrx-arco/icons-vue': ^0.3.1
  '@vueuse/core': ^13.1.0
  unplugin-vue-components: ^28.5.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - sharp
  - unrs-resolver
