import '@arco-design/web-vue/es/layout/style/index.js'
import '@arco-design/web-vue/es/space/style/index.js'
import '@arco-design/web-vue/es/typography/style/index.js'
import '@arco-design/web-vue/es/drawer/style/index.js'
import '@arco-design/web-vue/es/menu/style/index.js'
import '@arco-design/web-vue/es/breadcrumb/style/index.js'
import '@arco-design/web-vue/es/spin/style/index.js'
import '@arco-design/web-vue/es/scrollbar/style/index.js'
