import '@arco-design/web-vue/lib/layout/style/index.css'
import '@arco-design/web-vue/lib/space/style/index.css'
import '@arco-design/web-vue/lib/typography/style/index.css'
import '@arco-design/web-vue/lib/drawer/style/index.css'
import '@arco-design/web-vue/lib/menu/style/index.css'
import '@arco-design/web-vue/lib/breadcrumb/style/index.css'
import '@arco-design/web-vue/lib/spin/style/index.css'
import '@arco-design/web-vue/lib/style/index.css'
