import '@arco-design/web-vue/es/layout/style'
import '@arco-design/web-vue/es/space/style'
import '@arco-design/web-vue/es/typography/style'
import '@arco-design/web-vue/es/drawer/style'
import '@arco-design/web-vue/es/menu/style'
import '@arco-design/web-vue/es/breadcrumb/style'
import '@arco-design/web-vue/es/spin/style'
import '@arco-design/web-vue/es/scrollbar/style'
