import '@arco-design/web-vue/lib/layout/style'
import '@arco-design/web-vue/lib/space/style'
import '@arco-design/web-vue/lib/typography/style'
import '@arco-design/web-vue/lib/drawer/style'
import '@arco-design/web-vue/lib/menu/style'
import '@arco-design/web-vue/lib/breadcrumb/style'
import '@arco-design/web-vue/lib/spin/style'
import '@arco-design/web-vue/lib/scrollbar/style'
