import '@arco-design/web-vue/es/layout/style/index.css'
import '@arco-design/web-vue/es/space/style/index.css'
import '@arco-design/web-vue/es/typography/style/index.css'
import '@arco-design/web-vue/es/drawer/style/index.css'
import '@arco-design/web-vue/es/menu/style/index.css'
import '@arco-design/web-vue/es/breadcrumb/style/index.css'
import '@arco-design/web-vue/es/spin/style/index.css'
import '@arco-design/web-vue/es/style/index.css'
