export const mjsStyleCssComp = {
  ThemeDarkLight: ['@arco-design/web-vue/es/button/style/css.js'],
  ToggleFullScreen: ['@arco-design/web-vue/es/button/style/css.js'],
  AvatarDropDown: [
    '@arco-design/web-vue/es/avatar/style/css.js',
    '@arco-design/web-vue/es/dropdown/style/css.js',
  ],
  LoginForm: [
    '@arco-design/web-vue/es/button/style/css.js',
    '@arco-design/web-vue/es/checkbox/style/css.js',
    '@arco-design/web-vue/es/form/style/css.js',
    '@arco-design/web-vue/es/input/style/css.js',
    '@arco-design/web-vue/es/link/style/css.js',
    '@arco-design/web-vue/es/message/style/css.js',
    '@arco-design/web-vue/es/space/style/css.js',
  ],
  LoginPage: [
    '@arco-design/web-vue/es/button/style/css.js',
    '@arco-design/web-vue/es/checkbox/style/css.js',
    '@arco-design/web-vue/es/form/style/css.js',
    '@arco-design/web-vue/es/input/style/css.js',
    '@arco-design/web-vue/es/link/style/css.js',
    '@arco-design/web-vue/es/message/style/css.js',
    '@arco-design/web-vue/es/space/style/css.js',
    '@arco-design/web-vue/es/layout/style/css.js',
  ],
  SearchLayout: ['@arco-design/web-vue/es/layout/style/css.js'],
  SearchLayoutHeader: [
    '@arco-design/web-vue/es/card/style/css.js',
    '@arco-design/web-vue/es/divider/style/css.js',
    '@arco-design/web-vue/es/layout/style/css.js',
  ],
  SearchLayoutContent: [
    '@arco-design/web-vue/es/layout/style/css.js',
    '@arco-design/web-vue/es/tabs/style/css.js',
  ],
  ProCardList: [
    '@arco-design/web-vue/es/card/style/css.js',
    '@arco-design/web-vue/es/list/style/css.js',
    '@arco-design/web-vue/es/layout/style/css.js',
    '@arco-design/web-vue/es/pagination/style/css.js',
  ],
  ProCardMeta: [],
  ProPagination: [
    '@arco-design/web-vue/es/layout/style/css.js',
    '@arco-design/web-vue/es/pagination/style/css.js',
  ],
  ProList: [
    '@arco-design/web-vue/es/list/style/css.js',
    '@arco-design/web-vue/es/layout/style/css.js',
    '@arco-design/web-vue/es/pagination/style/css.js',
  ],
  SearchBar: [
    '@arco-design/web-vue/es/button/style/css.js',
    '@arco-design/web-vue/es/form/style/css.js',
    '@arco-design/web-vue/es/grid/style/css.js',
    '@arco-design/web-vue/es/space/style/css.js',
  ],
  SearchBarItem: [
    '@arco-design/web-vue/es/grid/style/css.js',
    '@arco-design/web-vue/es/form/style/css.js',
  ],
  FormGridItem: [],
  FormGrid: [],
  EditFormDialog: [
    '@arco-design/web-vue/es/drawer/style/css.js',
    '@arco-design/web-vue/es/form/style/css.js',
    '@arco-design/web-vue/es/modal/style/css.js',
    '@arco-design/web-vue/es/notification/style/css.js',
  ],
  SpaceDivider: ['@arco-design/web-vue/es/divider/style/css.js'],
}
export const mjsStyleJsComp = {
  ThemeDarkLight: ['@arco-design/web-vue/es/button/style/index.js'],
  ToggleFullScreen: ['@arco-design/web-vue/es/button/style/index.js'],
  AvatarDropDown: [
    '@arco-design/web-vue/es/avatar/style/index.js',
    '@arco-design/web-vue/es/dropdown/style/index.js',
  ],
  LoginForm: [
    '@arco-design/web-vue/es/button/style/index.js',
    '@arco-design/web-vue/es/checkbox/style/index.js',
    '@arco-design/web-vue/es/form/style/index.js',
    '@arco-design/web-vue/es/input/style/index.js',
    '@arco-design/web-vue/es/link/style/index.js',
    '@arco-design/web-vue/es/message/style/index.js',
    '@arco-design/web-vue/es/space/style/index.js',
  ],
  LoginPage: [
    '@arco-design/web-vue/es/button/style/index.js',
    '@arco-design/web-vue/es/checkbox/style/index.js',
    '@arco-design/web-vue/es/form/style/index.js',
    '@arco-design/web-vue/es/input/style/index.js',
    '@arco-design/web-vue/es/link/style/index.js',
    '@arco-design/web-vue/es/message/style/index.js',
    '@arco-design/web-vue/es/space/style/index.js',
    '@arco-design/web-vue/es/layout/style/index.js',
  ],
  SearchLayout: ['@arco-design/web-vue/es/layout/style/index.js'],
  SearchLayoutHeader: [
    '@arco-design/web-vue/es/card/style/index.js',
    '@arco-design/web-vue/es/divider/style/index.js',
    '@arco-design/web-vue/es/layout/style/index.js',
  ],
  SearchLayoutContent: [
    '@arco-design/web-vue/es/layout/style/index.js',
    '@arco-design/web-vue/es/tabs/style/index.js',
  ],
  ProCardList: [
    '@arco-design/web-vue/es/card/style/index.js',
    '@arco-design/web-vue/es/list/style/index.js',
    '@arco-design/web-vue/es/layout/style/index.js',
    '@arco-design/web-vue/es/pagination/style/index.js',
  ],
  ProCardMeta: [],
  ProPagination: [
    '@arco-design/web-vue/es/layout/style/index.js',
    '@arco-design/web-vue/es/pagination/style/index.js',
  ],
  ProList: [
    '@arco-design/web-vue/es/list/style/index.js',
    '@arco-design/web-vue/es/layout/style/index.js',
    '@arco-design/web-vue/es/pagination/style/index.js',
  ],
  SearchBar: [
    '@arco-design/web-vue/es/button/style/index.js',
    '@arco-design/web-vue/es/form/style/index.js',
    '@arco-design/web-vue/es/grid/style/index.js',
    '@arco-design/web-vue/es/space/style/index.js',
  ],
  SearchBarItem: [
    '@arco-design/web-vue/es/grid/style/index.js',
    '@arco-design/web-vue/es/form/style/index.js',
  ],
  FormGridItem: [],
  FormGrid: [],
  EditFormDialog: [
    '@arco-design/web-vue/es/drawer/style/index.js',
    '@arco-design/web-vue/es/form/style/index.js',
    '@arco-design/web-vue/es/modal/style/index.js',
    '@arco-design/web-vue/es/notification/style/index.js',
  ],
  SpaceDivider: ['@arco-design/web-vue/es/divider/style/index.js'],
}
export const vrxStyle = {
  ThemeDarkLight: [],
  ToggleFullScreen: [],
  AvatarDropDown: ['@vrx-arco/pro-components/style/AvatarDropDown/style/index.css'],
  LoginForm: ['@vrx-arco/pro-components/style/LoginForm/style/index.css'],
  LoginPage: [
    '@vrx-arco/pro-components/style/LoginForm/style/index.css',
    '@vrx-arco/pro-components/style/LoginPage/style/index.css',
  ],
  SearchLayout: ['@vrx-arco/pro-components/style/SearchLayout/style/index.css'],
  SearchLayoutHeader: [],
  SearchLayoutContent: [],
  ProCardList: [
    '@vrx-arco/pro-components/style/ProPagination/style/index.css',
    '@vrx-arco/pro-components/style/ProList/style/index.css',
  ],
  ProCardMeta: ['@vrx-arco/pro-components/style/ProCardMeta/style/index.css'],
  ProPagination: ['@vrx-arco/pro-components/style/ProPagination/style/index.css'],
  ProList: [
    '@vrx-arco/pro-components/style/ProPagination/style/index.css',
    '@vrx-arco/pro-components/style/ProList/style/index.css',
  ],
  SearchBar: ['@vrx-arco/pro-components/style/SearchBar/style/index.css'],
  SearchBarItem: [],
  FormGridItem: [],
  FormGrid: [],
  EditFormDialog: [],
  SpaceDivider: ['@vrx-arco/pro-components/style/SpaceDivider/style/index.css'],
}
