[[docs]]
name = "AvatarDropDown"
arco = ["Avatar", "Dropdown"]

[docs.slots]
default = { desc = "头像内部渲染插槽" }
content = { desc = "自定义下拉框渲染插槽" }

[docs.events]
select = { type = "[select: string]", desc = "下拉框选择事件" }

[[docs]]
name = "EditFormDialog"
arco = ["Drawer", "Form", "Modal", "Notification"]

[docs.slots]
default = { desc = "默认插槽" }

[docs.events]
confirm = { desc = "表单提交事件，使用该事件，会覆盖 props.add props.edit" }
success = { desc = "表单提交成功弹框关闭回调" }
close = { desc = "弹框关闭回调" }

[[docs]]
name = "LoginForm"
arco = ["Button", "Checkbox", "Form", "Input", "Link", "Message", "Space"]

[docs.slots]
title = { desc = "替换标题与副标题" }
form = { desc = "支持定义额外表单项" }
[docs.events]
submit = { desc = "提交事件，请注意该方法必须返回一个promise" }
forget = { desc = "忘记密码按钮点击事件" }
register = { desc = "注册按钮点击事件" }

[[docs]]
name = "LoginPage"
arco = [
  "Button",
  "Checkbox",
  "Form",
  "Input",
  "Link",
  "Message",
  "Space",
  "Layout",
]
style = ["LoginForm"]

[docs.slots]
logo = { desc = "logo" }
title = { desc = "title" }
bannerTitle = { desc = "左侧介绍页标题" }
bannerSubtitle = { desc = "左侧介绍页副标题" }
bannerImage = { desc = "左侧介绍页图片" }
formTitle = { desc = "登录表单标题" }
form = { desc = "支持定义额外表单项" }

[docs.events]
submit = { desc = "提交事件，请注意该方法必须返回一个promise" }
forget = { desc = "忘记密码按钮点击事件" }
register = { desc = "注册按钮点击事件" }


[[docs]]
name = "ProCardList"
arco = ["Card", "List", "Layout", "Pagination"]
style = ["ProPagination", "ProList"]

[docs.slots]
item = { desc = "列表当项渲染插槽" }
header = { desc = "顶部插槽" }

[docs.events]
pageChange = { desc = "表格分页pageNum改变" }
pageSizeChange = { desc = "表格pageSize改变" }
itemClick = { desc = "卡片列表项被点击事件" }


[[docs]]
name = "ProCardMeta"
arco = []

[docs.slots]
title = { desc = "标题" }
avatar = { desc = "头像" }
description = { desc = "描述" }
actions = { desc = "操作按钮" }

[[docs]]
name = "ProList"
arco = ["List", "Layout", "Pagination"]
style = ["ProPagination"]

[docs.slots]
item = { desc = "列表当项渲染插槽" }
header = { desc = "顶部插槽" }
[docs.events]
pageChange = { desc = "表格分页pageNum改变" }
pageSizeChange = { desc = "表格pageSize改变" }
scroll = { desc = "列表滚动时触发" }
reachBottom = { desc = "当列表到达底部时触发" }

[[docs]]
name = "ProPagination"
arco = ["Layout", "Pagination"]

[docs.slots]
default = { desc = "默认插槽，传递处理后的分页数据" }
header = { desc = "顶部插槽" }
[docs.events]
currentChange = { desc = "表格分页pageNum改变" }
pageSizeChange = { desc = "表格pageSize改变" }

[[docs]]
name = "SearchBar"
arco = ["Button", "Form", "Grid", "Space"]

[docs.slots]
default = { desc = "默认插槽" }

[docs.events]
search = { desc = "点击搜索按钮的回调，返回promise时，会自动显示加载动画" }
reset = { desc = "点击重置按钮的回调，返回promise时，会自动显示加载动画" }

[[docs]]
name = "SearchBarItem"
arco = ["Grid", "Form"]

[docs.slots]
default = { desc = "默认插槽" }

[[docs]]
name = "SearchLayoutContent"
arco = ["Layout", "Tabs"]

[docs.slots]
default = { desc = "默认插槽" }
tabExtra = { desc = "tab额外插槽" }

[docs.events]
tabChange = { desc = "内置tab切换事件" }

[[docs]]
name = "SearchLayoutHeader"
arco = ["Card", "Divider", "Layout"]

[docs.slots]
default = { desc = "默认插槽" }

[[docs]]
name = "SearchLayout"
arco = ["Layout"]

[docs.slots]
default = { desc = "默认插槽" }

[[docs]]
name = "SpaceDivider"
arco = ["Divider"]

[docs.slots]
default = { desc = "默认插槽" }

[[docs]]
name = "ThemeDarkLight"
arco = ["Button"]

[docs.events]
change = { desc = "暗色模式切换回调" }

[[docs]]
name = "ToggleFullScreen"
arco = ["Button"]
