/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ProCardList: typeof import('@vrx-arco/pro-components')['ProCardList']
    ProCardMeta: typeof import('@vrx-arco/pro-components')['ProCardMeta']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('@vrx-arco/pro-components')['SearchBar']
    SearchBarItem: typeof import('@vrx-arco/pro-components')['SearchBarItem']
    SearchLayout: typeof import('@vrx-arco/pro-components')['SearchLayout']
    SearchLayoutContent: typeof import('@vrx-arco/pro-components')['SearchLayoutContent']
    SearchLayoutHeader: typeof import('@vrx-arco/pro-components')['SearchLayoutHeader']
  }
}
